algo = input('\033[1;97mDigite algo: ')
print(f'O tipo primitivo de {algo} é {type(algo)}')
print(f'Só tem espaços? {algo.isspace()}')
print(f'É numérico? {algo.isnumeric()}')
print(f'É alfanumérico? {algo.isalnum()}')
print(f'É alfabético? {algo.isalpha()}')
print(f'Está em minúsculas? {algo.islower()}')
print(f'Está em maiúsculas? {algo.isupper()}')
print(f'Está capitalizada?  {algo.istitle()}\033[m')
