nome = str(input('Digite o seu nome completo: ')).strip()
nome_separado = nome.split()
letras_nome = len(nome) - nome.count(' ')
print('Analisando o seu nome...')
print(f'Seu nome em maiúsculas é {nome.upper()}')
print(f'Seu nome em minúsculas é {nome.lower()}')
print(f'Seu nome tem ao todo {letras_nome} letras')
print(f'Seu primeiro nome é {nome_separado[0]}, e ele tem um total de {len(nome_separado[0])} letras.')
